### ISSUE TITLE
how to run with enable_private_ip

### ISSUE THREAD

**Issue by gghtrt520** [shenjinti/browserlify#1]
I edit the .sh file with -- enable_private_ip true its not work

**Comment by shenjinti** [comment]
if you run with cargo:
```shell
cargo run -- --enable-private-ip
```
else with entrypoint.sh
```shell
/app/browserlify --enable-private-ip
```

The argument is `enable-private-ip` not `enable_private_ip`.

**Comment by gghtrt520** [comment]
tks
