### ISSUE TITLE
Cannot create

### ISSUE THREAD

**Issue by xuiam** [shenjinti/browserlify#2]
![image](https://github.com/shenjinti/browserlify/assets/42964379/36c0f315-20ee-42ac-b179-2d214e54170c)
Created according to the following method
![image](https://github.com/shenjinti/browserlify/assets/42964379/08a99745-5bc7-49ff-92a6-688d942232a9)
Description Failed to create the remote browse
![image](https://github.com/shenjinti/browserlify/assets/42964379/3b8364be-52cd-4dc7-bec1-76b636714930)

**Comment by 704572066** [comment]
docker镜像怎么下载不了
